const I18N={
 ru:{brand:'Цветочная сила',subtitle:'Уход, который легко помнить',types:'Типы растений',plants:'Мои растения',newType:'Новый тип',newPlant:'Добавить растение',typeName:'Название типа',care:'Инструкция по уходу',save:'Сохранить',plantName:'Имя растения',chooseType:'Выберите тип',bought:'Дата покупки',photo:'Фотография',qr:'QR-код для горшка',download:'Скачать QR',view:'Посмотреть инфо',water:'Полито',fertilize:'Опрыскано удобрением',lastCare:'История ухода',never:'Пока нет записей',back:'Назад в кабинет',emptyTypes:'Добавьте первый тип растения',emptyPlants:'Здесь появятся ваши растения',watered:'Полив отмечен',fed:'Удобрение отмечено',edit:'Изменить',delete:'Удалить',cancel:'Отмена',today:'Сегодня',takePhoto:'Сфотографировать растение',uploading:'Отправляем фотографию…',photoSaved:'Фотография сохранена',photoError:'Фото сохранено только на этом устройстве'},
 en:{brand:'Flower Power',subtitle:'Plant care, easy to remember',types:'Plant types',plants:'My plants',newType:'New type',newPlant:'Add plant',typeName:'Type name',care:'Care instructions',save:'Save',plantName:'Plant name',chooseType:'Choose a type',bought:'Purchase date',photo:'Photo',qr:'Pot QR code',download:'Download QR',view:'View info',water:'Watered',fertilize:'Fertilizer sprayed',lastCare:'Care history',never:'No records yet',back:'Back to dashboard',emptyTypes:'Add your first plant type',emptyPlants:'Your plants will appear here',watered:'Watering recorded',fed:'Fertilizing recorded',edit:'Edit',delete:'Delete',cancel:'Cancel',today:'Today',takePhoto:'Take a plant photo',uploading:'Uploading photo…',photoSaved:'Photo saved',photoError:'Could not upload photo'},
 sr:{brand:'Snaga cveća',subtitle:'Nega biljaka koja se lako pamti',types:'Vrste biljaka',plants:'Moje biljke',newType:'Nova vrsta',newPlant:'Dodaj biljku',typeName:'Naziv vrste',care:'Uputstvo za negu',save:'Sačuvaj',plantName:'Ime biljke',chooseType:'Izaberite vrstu',bought:'Datum kupovine',photo:'Fotografija',qr:'QR kod za saksiju',download:'Preuzmi QR',view:'Pogledaj informacije',water:'Zaliveno',fertilize:'Poprskano đubrivom',lastCare:'Istorija nege',never:'Još nema zapisa',back:'Nazad na kontrolnu tablu',emptyTypes:'Dodajte prvu vrstu biljke',emptyPlants:'Vaše biljke će se pojaviti ovde',watered:'Zalivanje zabeleženo',fed:'Đubrenje zabeleženo',edit:'Izmeni',delete:'Obriši',cancel:'Otkaži',today:'Danas',takePhoto:'Fotografiši biljku',uploading:'Šaljemo fotografiju…',photoSaved:'Fotografija je sačuvana',photoError:'Slanje fotografije nije uspelo'}
};
const runtimeConfig=await fetch('./api/config').then(response=>response.ok?response.json():{}).catch(()=>({}));
const seed={types:[{id:'t1',name:'Монстера',care:'Яркий рассеянный свет. Поливать после просыхания верхних 3–5 см почвы.'},{id:'t2',name:'Фикус',care:'Умеренный свет, без сквозняков. Поливать раз в 7–10 дней.'}],plants:[{id:'p1',name:'Моника',typeId:'t1',bought:'2026-05-18',photo:'',events:[{kind:'water',date:new Date(Date.now()-864e5).toISOString()}]}]};
let data=JSON.parse(localStorage.getItem('flower-power-data')||'null')||seed;
let lang=localStorage.getItem('flower-power-lang')||'ru';
let modal=null, toast='';
const t=k=>I18N[lang][k]||k; const save=()=>localStorage.setItem('flower-power-data',JSON.stringify(data));
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=`<svg viewBox="0 0 48 48"><path d="M24 42V22M24 29c-10 0-16-6-16-16 10 0 16 6 16 16Zm0-7c0-10 6-16 16-16 0 10-6 16-16 16Z"/></svg>`;
function shell(content,client=false){return `<header><a class="logo" href="#">${icon}<span>${t('brand')}<small>${t('subtitle')}</small></span></a><div class="langs">${['ru','en','sr'].map(x=>`<button class="${x===lang?'active':''}" data-lang="${x}">${x.toUpperCase()}</button>`).join('')}</div></header><main class="${client?'client':''}">${content}</main>${toast?`<div class="toast">✓ ${toast}</div>`:''}`}
function dashboard(){let types=data.types.map(x=>`<article class="type-card"><div class="plant-icon">${icon}</div><div><h3>${esc(x.name)}</h3><p>${esc(x.care)}</p></div><div class="actions"><button data-edit-type="${x.id}">${t('edit')}</button><button data-del-type="${x.id}">×</button></div></article>`).join('')||`<div class="empty">${t('emptyTypes')}</div>`;
let plants=data.plants.map(p=>{let ty=data.types.find(x=>x.id===p.typeId);return `<article class="plant-card">${p.photo?`<img src="${p.photo}" alt="">`:`<div class="placeholder">${icon}</div>`}<div class="plant-body"><span class="tag">${esc(ty?.name||'—')}</span><h3>${esc(p.name)}</h3><p>${t('bought')}: ${p.bought||'—'}</p><div class="card-buttons"><a href="#plant/${p.id}">${t('view')}</a><button data-qr="${p.id}">▦ ${t('qr')}</button></div></div></article>`}).join('')||`<div class="empty">${t('emptyPlants')}</div>`;
return shell(`<section class="hero"><div><span class="eyebrow">PLANT CARE STUDIO</span><h1>${t('brand')}</h1><p>${t('subtitle')}</p></div><div class="hero-leaves">${icon}</div></section><section><div class="section-head"><div><span>01</span><h2>${t('types')}</h2></div><button class="primary" data-open="type">＋ ${t('newType')}</button></div><div class="types-grid">${types}</div></section><section><div class="section-head"><div><span>02</span><h2>${t('plants')}</h2></div><button class="primary" data-open="plant">＋ ${t('newPlant')}</button></div><div class="plants-grid">${plants}</div></section>${modalHTML()}`)}
function clientPage(id){let p=data.plants.find(x=>x.id===id);if(!p)return shell(`<div class="empty">Plant not found</div>`,true);let ty=data.types.find(x=>x.id===p.typeId);let events=[...(p.events||[])].reverse().map(e=>`<li><i class="${e.kind}"></i><span>${e.kind==='water'?t('water'):t('fertilize')}</span><time>${new Date(e.date).toLocaleString(lang)}</time></li>`).join('')||`<p>${t('never')}</p>`;return shell(`<a class="back" href="#">← ${t('back')}</a><article class="profile"><div class="profile-photo">${p.photo?`<img src="${p.photo}">`:icon}</div><div class="profile-title"><span class="tag">${esc(ty?.name||'—')}</span><h1>${esc(p.name)}</h1><p>${t('bought')}: ${p.bought||'—'}</p><label class="camera-button">📷 ${t('takePhoto')}<input data-camera type="file" accept="image/*" capture="environment"></label></div></article><div class="client-actions"><button data-info>ⓘ<span>${t('view')}</span></button><button class="water" data-event="water">💧<span>${t('water')}</span></button><button class="feed" data-event="feed">✦<span>${t('fertilize')}</span></button></div><section class="care-info"><h2>${t('care')}</h2><p>${esc(ty?.care||'—')}</p></section><section class="history"><h2>${t('lastCare')}</h2><ul>${events}</ul></section>`,true)}
function modalHTML(){if(!modal)return '';if(modal.kind==='qr'){let p=data.plants.find(x=>x.id===modal.id);return `<div class="overlay"><div class="dialog qr-dialog"><button class="close">×</button><span class="tag">${t('qr')}</span><h2>${esc(p.name)}</h2><img id="qr" src="${qrUrl(p.id)}" alt="QR"><a class="primary download" href="${qrUrl(p.id)}" download="plant-qr.png">↓ ${t('download')}</a></div></div>`}let isType=modal.kind==='type', item=isType?data.types.find(x=>x.id===modal.id):null;return `<div class="overlay"><form class="dialog" id="editor"><button type="button" class="close">×</button><h2>${isType?t('newType'):t('newPlant')}</h2>${isType?`<label>${t('typeName')}<input name="name" required value="${esc(item?.name)}"></label><label>${t('care')}<textarea name="care" required>${esc(item?.care)}</textarea></label>`:`<label>${t('plantName')}<input name="name" required></label><label>${t('chooseType')}<select name="typeId" required><option value="">—</option>${data.types.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`)}</select></label><label>${t('bought')}<input type="date" name="bought"></label><label>${t('photo')}<input type="file" name="photo" accept="image/*"></label>`}<div class="form-actions"><button type="button" class="secondary close">${t('cancel')}</button><button class="primary">${t('save')}</button></div></form></div>`}
function qrUrl(id){let plant=data.plants.find(item=>item.id===id),type=data.types.find(item=>item.id===plant?.typeId);let payload=encodePayload({plant:{...plant,photo:'',events:[]},type});let base=runtimeConfig.publicUrl||location.href.split('#')[0];let target=`${base.replace(/#.*$/,'')}#plant/${id}?data=${payload}`;return `https://api.qrserver.com/v1/create-qr-code/?size=300x300&color=173d2a&bgcolor=fffdf7&data=${encodeURIComponent(target)}`}
function encodePayload(value){let bytes=new TextEncoder().encode(JSON.stringify(value)),binary='';bytes.forEach(byte=>binary+=String.fromCharCode(byte));return btoa(binary).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function route(){let match=location.hash.match(/^#plant\/([^?]+)(?:\?data=(.+))?$/);if(!match)return null;if(match[2]&&!data.plants.some(item=>item.id===match[1]))try{let binary=atob(match[2].replaceAll('-','+').replaceAll('_','/')),bytes=Uint8Array.from(binary,char=>char.charCodeAt(0)),payload=JSON.parse(new TextDecoder().decode(bytes));if(payload.type&&!data.types.some(item=>item.id===payload.type.id))data.types.push(payload.type);if(payload.plant)data.plants.push(payload.plant);save()}catch{}return match[1]}
function render(){let id=route();document.documentElement.lang=lang;document.querySelector('#app').innerHTML=id?clientPage(id):dashboard();bind()}
function bind(){document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;localStorage.setItem('flower-power-lang',lang);render()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{modal={kind:b.dataset.open};render()});document.querySelectorAll('.close').forEach(b=>b.onclick=()=>{modal=null;render()});document.querySelectorAll('[data-edit-type]').forEach(b=>b.onclick=()=>{modal={kind:'type',id:b.dataset.editType};render()});document.querySelectorAll('[data-del-type]').forEach(b=>b.onclick=()=>{data.types=data.types.filter(x=>x.id!==b.dataset.delType);save();render()});document.querySelectorAll('[data-qr]').forEach(b=>b.onclick=()=>{modal={kind:'qr',id:b.dataset.qr};render()});let form=document.querySelector('#editor');if(form)form.onsubmit=e=>{e.preventDefault();let f=new FormData(form);if(modal.kind==='type'){let old=data.types.find(x=>x.id===modal.id);if(old){old.name=f.get('name');old.care=f.get('care')}else data.types.push({id:crypto.randomUUID(),name:f.get('name'),care:f.get('care')});save();modal=null;render()}else{let file=f.get('photo');let finish=photo=>{data.plants.push({id:crypto.randomUUID(),name:f.get('name'),typeId:f.get('typeId'),bought:f.get('bought'),photo,events:[]});save();modal=null;render()};if(file?.size){let r=new FileReader();r.onload=()=>finish(r.result);r.readAsDataURL(file)}else finish('')}};document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{let id=route(),p=data.plants.find(x=>x.id===id),kind=b.dataset.event;p.events=p.events||[];p.events.push({kind,date:new Date().toISOString()});save();toast=kind==='water'?t('watered'):t('fed');render();setTimeout(()=>{toast='';render()},1800)});let camera=document.querySelector('[data-camera]');if(camera)camera.onchange=()=>uploadPhoto(camera)}
async function uploadPhoto(input){let file=input.files?.[0];if(!file)return;let id=route(),plant=data.plants.find(x=>x.id===id);toast=t('uploading');render();let image=await readImage(file);try{let response=await fetch(`./api/plants/${encodeURIComponent(id)}/photo`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image})});if(!response.ok)throw new Error('Upload failed');let result=await response.json();plant.photo=result.url;toast=t('photoSaved')}catch{plant.photo=image;toast=t('photoError')}save();render();setTimeout(()=>{toast='';render()},2200)}
function readImage(file){return new Promise((resolve,reject)=>{let reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})}
addEventListener('hashchange',()=>{modal=null;render()});render();
